### ISSUE TITLE
Не работает по неизвестным причинам

### ISSUE THREAD

**Issue by Fearcatcher** [neizerth/beast-companion#1]
Здравствуйте.

Я обладатель Apple iPhone XR iOS 14.3, Apple iPad 10,5 iOS 14.3, и, к сожалению, на данных системах сайт не работает. При нажатии любой из кнопок ничего не происходит, кроме анимации нажатия, то есть карта не открывается. Пробовал семь разных браузеров: Safari, Chrome, Firefox, Yandex, Puffin, Aloha, встроенный в Documents. На ПК с Windows 10 и Android 11 все отлично. Если я могу как-то помочь в тестировании для разрешения проблемы, то буду рад, ибо как я понял, я один с такой проблемой, и у других "яблоководов" все отлично работает.

**Comment by neizerth** [comment]
Решено!
